function T = v1OptionTable()
%GEO.INTERNAL.V1OPTIONTABLE  Every geoImagesc option, and where it went.
%
%   SYNTAX
%     T = GEO.INTERNAL.V1OPTIONTABLE()
%
%   DESCRIPTION
%     The single authority on what happened to each of v1 geoImagesc's
%     120 options. One row per option, and every row is one of six
%     kinds - there is no seventh, and "not listed" is not a state a
%     name can be in, because the test reads v1's source and requires
%     every declared option to appear here.
%
%     THE KINDS, and why six rather than a rename column:
%
%       "opt"    forwards to an element's option of the given name.
%       "toggle" is a v1 logical that switches a geo.map element on or
%                off - v1 wrote Graticule = false, and so does v2.
%       "map"    is a geo.map option in its own right.
%       "crs"    is a GEO.CRS construction option; v1's six loose
%                projection settings became one validated value.
%       "merge"  is the case a rename table cannot express: TWO v1
%                options became ONE v2 option. NorthArrowColor1 and
%                NorthArrowColor2 are rows 1 and 2 of geo.northarrow's
%                Colors, so a translator has to accumulate rather than
%                substitute.
%       "none"   has no v2 equivalent, and the Note says what to do
%                instead. This is the only kind that raises, and it
%                raises with the replacement named - a v1 script that
%                used it gets an instruction, not "unrecognised".
%
%     NOTHING HERE IS GUESSED. The inventory's own rule is that an
%     option no rule matched is unmapped and never guessed, and
%     RECORDS/V1_OPTION_RESOLUTION verifies every "opt" and "merge" row
%     against the target function's real arguments block. A row naming
%     an option that does not exist fails the suite.
%
%   INPUTS
%     (none)
%
%   OUTPUTS
%     T  (1,:) struct  Fields:
%          V1     (1,1) string  The v1 option name, exactly as spelled.
%          Kind   (1,1) string  One of the six above.
%          Target (1,1) string  The geo.map option, or "" for map/crs.
%          Option (1,1) string  The v2 name, or the merge target.
%          Note   (1,1) string  Why, for "none" and "merge" rows.
%
%   ACCURACY
%     Exact: a name either matches v1's declaration or it does not, and
%     a destination either exists in the target's arguments block or it
%     does not. No tolerance applies.
%
%   ERRORS
%     (none raised; this is a table)
%
%   EXAMPLE
%     T = geo.internal.v1OptionTable();
%     T(strcmp([T.V1], "GraticuleColor"))
%
%   LIMITATIONS
%     geoImagesc only. The other four v1 fronts get their own rows when
%     geo.trackmap, geo.pointmap, geo.timeseries and geo.panel are
%     written; sharing this table before those exist would mean guessing
%     at their destinations.
%
%   See also GEO.INTERNAL.V1OPTIONS, GEO.MAP, V1_OPTION_RESOLUTION.
%
%   ---------------------------------------------------------------------
%   geoMap v2.0 | 16-Aug-2026 | Claude Opus 5 (Anthropic)

r = @(v, k, t, o, n) struct('V1', string(v), 'Kind', string(k), ...
    'Target', string(t), 'Option', string(o), 'Note', string(n));

readGrid = "topography is read by geo.readGrid now, before the map is " + ...
    "drawn: geo.map takes a grid, it does not fetch one. " + ...
    "G = geo.readGrid(file, ...) then geo.map(G, crs).";
locator = "the locator inset chooses its own projection centred on the " + ...
    "map, so it cannot be aimed independently. v1 let the two disagree.";
byCorner = "elements are placed by named corner now (Location = " + ...
    """northeast"" and the rest), and pushed clear of each other by the " + ...
    "layout manager. A figure-fraction or lon/lat position cannot do that.";
lighting = "banned by D-009: renderer-dependent output (F9). geo.hillshade " + ...
    "computes shading numerically instead, and is reproducible.";

T = [ ...
    ... % ---- the projection, now one validated value ----
    r("Projection","crs","","name","") ...
    r("CenterLongitude","crs","","CenterLongitude","") ...
    r("CenterLatitude","crs","","CenterLatitude","") ...
    r("Hemisphere","crs","","Hemisphere","") ...
    r("StandardParallel","crs","","StandardParallel","") ...
    r("StandardParallel2","crs","","StandardParallel2","") ...
    ... % ---- area of interest ----
    r("AreaOfInterest","data","Region","R","") ...
    r("ShowAreaOfInterestOutline","toggle","Region","","") ...
    r("AreaOfInterestColor","opt","Region","Color","") ...
    r("AreaOfInterestWidth","opt","Region","LineWidth","") ...
    r("AreaOfInterestPadding","none","","", ...
      "padding belongs to the region, not to the map: " + ...
      "geo.region(spec, Padding = 0.1) then Region = struct(R = that).") ...
    ... % ---- the basemap ----
    r("ColormapName","opt","Basemap","ColormapName","") ...
    r("Colormap","opt","Basemap","Colormap","") ...
    r("CLim","opt","Basemap","CLim","") ...
    r("CLimMode","opt","Basemap","CLimMode","") ...
    r("CLimPercentile","opt","Basemap","CLimPercentile","") ...
    r("DiscreteLevels","opt","Basemap","DiscreteLevels","") ...
    r("NaNColor","opt","Basemap","NaNColor","") ...
    r("Mask","opt","Basemap","Mask","") ...
    r("MaskMethod","opt","Basemap","MaskMethod","") ...
    r("MaskThreshold","opt","Basemap","MaskThreshold","") ...
    r("MaskPolygon","opt","Basemap","MaskPolygon","") ...
    r("MaskPolygonSide","opt","Basemap","MaskPolygonSide","") ...
    r("MaskColor","opt","Basemap","MaskColor","") ...
    r("MaskThresholdSide","none","","", ...
      "geo.basemap masks below the threshold. To mask above it, negate " + ...
      "the field and the threshold together, or use MaskMethod = " + ...
      """polygon"". v1's ""above"" is not available.") ...
    r("Parent","map","","Parent","") ...
    ... % ---- shading ----
    r("Illuminate","toggle","Basemap","Hillshade","") ...
    r("LightAzimuth","opt","Basemap","Azimuth","") ...
    r("LightElevation","opt","Basemap","Elevation","") ...
    r("AmbientStrength","opt","Basemap","Ambient","") ...
    r("SpecularStrength","none","","", lighting) ...
    r("Material","none","","", lighting) ...
    r("VerticalExaggeration","none","","", ...
      "geo.basemap does not expose the shading z-factor. Call " + ...
      "geo.hillshade(G, ZFactor = ...) and pass the result as the map's " + ...
      "colour field, or leave it: the default is scaled to the data.") ...
    ... % ---- topography reading, now an L2 step ----
    r("TopographyLon","none","","", readGrid) ...
    r("TopographyLat","none","","", readGrid) ...
    r("TopographyWorldFile","none","","", readGrid) ...
    r("TopographyVariable","none","","", readGrid) ...
    r("DownsampleTopography","none","","", readGrid) ...
    r("MaxGridSize","none","","", readGrid) ...
    ... % ---- graticule ----
    r("Graticule","toggle","Graticule","","") ...
    r("GraticuleStepLon","opt","Graticule","StepLon","") ...
    r("GraticuleStepLat","opt","Graticule","StepLat","") ...
    r("GraticuleColor","opt","Graticule","Color","") ...
    r("GraticuleLabels","opt","Graticule","Labels","") ...
    r("LongitudeLabelEdge","opt","Graticule","LonLabelEdge","") ...
    r("LatitudeLabelEdge","opt","Graticule","LatLabelEdge","") ...
    r("LongitudeLabelRotation","none","","", ...
      "graticule labels are horizontal in v2. v1 rotated them from a " + ...
      "tangent heuristic; labels are placed by geo.unproject at the " + ...
      "frame edge now, where a rotation has nothing to follow.") ...
    r("LatitudeLabelRotation","none","","", ...
      "graticule labels are horizontal in v2; see LongitudeLabelRotation.") ...
    r("LongitudeLabelOffset","none","","", ...
      "the label gap is one setting for both edges and is a FRACTION OF " + ...
      "THE MAP DIAGONAL, not degrees: Graticule = struct(LabelGap = " + ...
      "0.034). Translating the degree value would silently change it.") ...
    r("LatitudeLabelOffset","none","","", ...
      "see LongitudeLabelOffset: one LabelGap, in diagonals, not degrees.") ...
    ... % ---- frame ----
    r("SegmentedFrame","none","","", ...
      "the v2 frame is always segmented - that is what a map frame is - " + ...
      "so there is nothing to switch. Frame = false removes it entirely; " + ...
      "Frame = struct(Segments = 1) is the nearest thing to a plain one.") ...
    r("FrameSegments","opt","Frame","Segments","") ...
    r("FrameThickness","opt","Frame","Thickness","") ...
    r("FrameColors","opt","Frame","Colors","") ...
    ... % ---- north arrow ----
    r("NorthArrow","toggle","NorthArrow","","") ...
    r("NorthArrowLocation","opt","NorthArrow","Location","") ...
    r("NorthArrowThickness","opt","NorthArrow","LineWidth","") ...
    r("NorthArrowFontSize","opt","NorthArrow","FontSize","") ...
    r("NorthArrowColor1","merge","NorthArrow","Colors", "row 1") ...
    r("NorthArrowColor2","merge","NorthArrow","Colors", "row 2") ...
    r("NorthArrowLatLon","none","","", byCorner) ...
    r("NorthArrowFigurePos","none","","", byCorner) ...
    ... % ---- locator inset ----
    r("MapInset","toggle","Inset","","") ...
    r("MapInsetLocation","opt","Inset","Location","") ...
    r("MapInsetSize","opt","Inset","Size","") ...
    r("MapInsetBorderColor","opt","Inset","Border","") ...
    r("MapInsetBorderWidth","opt","Inset","BorderWidth","") ...
    r("MapInsetCoastlineColor","opt","Inset","Coast","") ...
    r("MapInsetBackgroundColor","opt","Inset","Ocean","") ...
    r("MapInsetFrameColor","opt","Inset","ExtentColor","") ...
    r("MapInsetFrameWidth","opt","Inset","ExtentWidth","") ...
    r("MapInsetProjection","none","","", locator) ...
    r("MapInsetCenterLongitude","none","","", locator) ...
    r("MapInsetCenterLatitude","none","","", locator) ...
    r("MapInsetStandardParallel","none","","", locator) ...
    r("MapInsetStandardParallel2","none","","", locator) ...
    r("MapInsetStyle","none","","", ...
      "the locator's look is three colours - Ocean, Land and Coast - " + ...
      "rather than a named style, so it can be matched to the map.") ...
    ... % ---- scale bar ----
    r("ScaleBar","toggle","ScaleBar","","") ...
    r("ScaleBarUnits","opt","ScaleBar","Units","") ...
    r("ScaleBarLocation","opt","ScaleBar","Location","") ...
    r("ScaleBarThickness","opt","ScaleBar","Thickness","") ...
    r("ScaleBarLatLon","none","","", byCorner) ...
    r("ScaleBarFigurePos","none","","", byCorner) ...
    r("ScaleBarLabelColor","none","","", ...
      "the bar's label takes the bar's own colour, so the two cannot " + ...
      "drift apart. Set ScaleBar = struct(Colors = [c1; c2]).") ...
    ... % ---- coastlines and rivers ----
    r("Coastlines","toggle","Coastline","","") ...
    r("Coastline","opt","Coastline","Source","") ...
    r("CoastlineColor","opt","Coastline","Color","") ...
    r("CoastlineWidth","opt","Coastline","LineWidth","") ...
    r("Rivers","toggle","Rivers","","") ...
    r("River","opt","Rivers","Source","") ...
    r("RiverColor","opt","Rivers","Color","") ...
    r("RiverWidth","opt","Rivers","LineWidth","") ...
    ... % ---- contours ----
    r("Contour","toggle","Contours","","") ...
    r("ContourLevels","opt","Contours","Levels","") ...
    r("ContourColor","opt","Contours","Color","") ...
    r("ContourWidth","opt","Contours","LineWidth","") ...
    r("ContourLabels","opt","Contours","Labels","") ...
    ... % ---- scattered points ----
    r("Points","data","Points","P","") ...
    r("PointMarker","opt","Points","Marker","") ...
    r("PointSize","opt","Points","MarkerSize","") ...
    r("PointColormap","opt","Points","Colormap","") ...
    r("PointSizeRange","opt","Points","SizeRange","") ...
    r("PointLabels","none","","", ...
      "labels belong to the points: geo.points(lon, lat, Labels = ...). " + ...
      "A value struct carries its own data so an overlay cannot be " + ...
      "handed coordinates and labels of different lengths.") ...
    r("PointColorData","none","","", ...
      "colour comes from the points' Obs: geo.points(lon, lat, Obs = ...).") ...
    r("PointSizeData","none","","", ...
      "size comes from the points' SizeData: geo.points(lon, lat, " + ...
      "SizeData = ...). v1 overloaded ONE vector for colour and size, so " + ...
      "size-by-magnitude with colour-by-sign was impossible.") ...
    r("PointColor","none","","", ...
      "points are coloured by Obs through the colormap. For one flat " + ...
      "colour give every point the same Obs and a one-colour Colormap.") ...
    ... % ---- colorbar ----
    r("ShowColorbar","toggle","Colorbar","","") ...
    r("ColorbarLocation","opt","Colorbar","Location","") ...
    r("ColorbarLabel","opt","Colorbar","Label","") ...
    r("ColorbarStyle","opt","Colorbar","Style","") ...
    r("ColorbarLabelSide","opt","Colorbar","LabelSide","") ...
    r("ColorbarArrows","opt","Colorbar","Arrows","") ...
    r("ColorbarSubticks","opt","Colorbar","Subticks","") ...
    ... % ---- the front's own ----
    r("Title","map","","Title","") ...
    r("FontName","map","","FontName","") ...
    r("FontSize","map","","FontSize","") ...
    r("ExportPath","map","","Export","") ...
    r("ExportResolution","export","","Resolution","") ...
    r("FigureSize","none","","", ...
      "a figure size in PIXELS does not describe a page. geo.export " + ...
      "takes Width and Height in centimetres and delivers them: " + ...
      "Export = ""fig.pdf"", ExportOptions = struct(Width = 17).") ...
    r("Style","none","","", ...
      "v1's Style bundled FontName, FontSize and ExportResolution. Those " + ...
      "are three options and are set as three; a preset that silently " + ...
      "moved settings a caller had not named was worth losing.") ...
    ];
end
